//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        private int AnFabricatieField;
        
        private int KilometrajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PozaField;
        
        private decimal PretField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int AnFabricatie {
            get {
                return this.AnFabricatieField;
            }
            set {
                if ((this.AnFabricatieField.Equals(value) != true)) {
                    this.AnFabricatieField = value;
                    this.RaisePropertyChanged("AnFabricatie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Kilometraj {
            get {
                return this.KilometrajField;
            }
            set {
                if ((this.KilometrajField.Equals(value) != true)) {
                    this.KilometrajField = value;
                    this.RaisePropertyChanged("Kilometraj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Poza {
            get {
                return this.PozaField;
            }
            set {
                if ((object.ReferenceEquals(this.PozaField, value) != true)) {
                    this.PozaField = value;
                    this.RaisePropertyChanged("Poza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal Pret {
            get {
                return this.PretField;
            }
            set {
                if ((this.PretField.Equals(value) != true)) {
                    this.PretField = value;
                    this.RaisePropertyChanged("Pret");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CarWebServiceSoap")]
    public interface CarWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllCarsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCars", ReplyAction="*")]
        Client.ServiceReference1.GetAllCarsResponse GetAllCars(Client.ServiceReference1.GetAllCarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCars", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetAllCarsResponse> GetAllCarsAsync(Client.ServiceReference1.GetAllCarsRequest request);
        
        // CODEGEN: Generating message contract since element name car from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCar", ReplyAction="*")]
        Client.ServiceReference1.AddCarResponse AddCar(Client.ServiceReference1.AddCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCar", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddCarResponse> AddCarAsync(Client.ServiceReference1.AddCarRequest request);
        
        // CODEGEN: Generating message contract since element name car from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCar", ReplyAction="*")]
        Client.ServiceReference1.UpdateCarResponse UpdateCar(Client.ServiceReference1.UpdateCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCar", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.UpdateCarResponse> UpdateCarAsync(Client.ServiceReference1.UpdateCarRequest request);
        
        // CODEGEN: Generating message contract since element name car from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCar", ReplyAction="*")]
        Client.ServiceReference1.DeleteCarResponse DeleteCar(Client.ServiceReference1.DeleteCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCar", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.DeleteCarResponse> DeleteCarAsync(Client.ServiceReference1.DeleteCarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCars", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetAllCarsRequestBody Body;
        
        public GetAllCarsRequest() {
        }
        
        public GetAllCarsRequest(Client.ServiceReference1.GetAllCarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCarsRequestBody {
        
        public GetAllCarsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCarsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetAllCarsResponseBody Body;
        
        public GetAllCarsResponse() {
        }
        
        public GetAllCarsResponse(Client.ServiceReference1.GetAllCarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.Car[] GetAllCarsResult;
        
        public GetAllCarsResponseBody() {
        }
        
        public GetAllCarsResponseBody(Client.ServiceReference1.Car[] GetAllCarsResult) {
            this.GetAllCarsResult = GetAllCarsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCar", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddCarRequestBody Body;
        
        public AddCarRequest() {
        }
        
        public AddCarRequest(Client.ServiceReference1.AddCarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.Car car;
        
        public AddCarRequestBody() {
        }
        
        public AddCarRequestBody(Client.ServiceReference1.Car car) {
            this.car = car;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddCarResponseBody Body;
        
        public AddCarResponse() {
        }
        
        public AddCarResponse(Client.ServiceReference1.AddCarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddCarResponseBody {
        
        public AddCarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCar", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.UpdateCarRequestBody Body;
        
        public UpdateCarRequest() {
        }
        
        public UpdateCarRequest(Client.ServiceReference1.UpdateCarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.Car car;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newModel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newMarca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string newAnDeFabricatie;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string newKm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string newPret;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string newPoza;
        
        public UpdateCarRequestBody() {
        }
        
        public UpdateCarRequestBody(Client.ServiceReference1.Car car, string newModel, string newMarca, string newAnDeFabricatie, string newKm, string newPret, string newPoza) {
            this.car = car;
            this.newModel = newModel;
            this.newMarca = newMarca;
            this.newAnDeFabricatie = newAnDeFabricatie;
            this.newKm = newKm;
            this.newPret = newPret;
            this.newPoza = newPoza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.UpdateCarResponseBody Body;
        
        public UpdateCarResponse() {
        }
        
        public UpdateCarResponse(Client.ServiceReference1.UpdateCarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateCarResponseBody {
        
        public UpdateCarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCar", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.DeleteCarRequestBody Body;
        
        public DeleteCarRequest() {
        }
        
        public DeleteCarRequest(Client.ServiceReference1.DeleteCarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteCarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.Car car;
        
        public DeleteCarRequestBody() {
        }
        
        public DeleteCarRequestBody(Client.ServiceReference1.Car car) {
            this.car = car;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.DeleteCarResponseBody Body;
        
        public DeleteCarResponse() {
        }
        
        public DeleteCarResponse(Client.ServiceReference1.DeleteCarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteCarResponseBody {
        
        public DeleteCarResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarWebServiceSoapChannel : Client.ServiceReference1.CarWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarWebServiceSoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.CarWebServiceSoap>, Client.ServiceReference1.CarWebServiceSoap {
        
        public CarWebServiceSoapClient() {
        }
        
        public CarWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.GetAllCarsResponse Client.ServiceReference1.CarWebServiceSoap.GetAllCars(Client.ServiceReference1.GetAllCarsRequest request) {
            return base.Channel.GetAllCars(request);
        }
        
        public Client.ServiceReference1.Car[] GetAllCars() {
            Client.ServiceReference1.GetAllCarsRequest inValue = new Client.ServiceReference1.GetAllCarsRequest();
            inValue.Body = new Client.ServiceReference1.GetAllCarsRequestBody();
            Client.ServiceReference1.GetAllCarsResponse retVal = ((Client.ServiceReference1.CarWebServiceSoap)(this)).GetAllCars(inValue);
            return retVal.Body.GetAllCarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetAllCarsResponse> Client.ServiceReference1.CarWebServiceSoap.GetAllCarsAsync(Client.ServiceReference1.GetAllCarsRequest request) {
            return base.Channel.GetAllCarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GetAllCarsResponse> GetAllCarsAsync() {
            Client.ServiceReference1.GetAllCarsRequest inValue = new Client.ServiceReference1.GetAllCarsRequest();
            inValue.Body = new Client.ServiceReference1.GetAllCarsRequestBody();
            return ((Client.ServiceReference1.CarWebServiceSoap)(this)).GetAllCarsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.AddCarResponse Client.ServiceReference1.CarWebServiceSoap.AddCar(Client.ServiceReference1.AddCarRequest request) {
            return base.Channel.AddCar(request);
        }
        
        public void AddCar(Client.ServiceReference1.Car car) {
            Client.ServiceReference1.AddCarRequest inValue = new Client.ServiceReference1.AddCarRequest();
            inValue.Body = new Client.ServiceReference1.AddCarRequestBody();
            inValue.Body.car = car;
            Client.ServiceReference1.AddCarResponse retVal = ((Client.ServiceReference1.CarWebServiceSoap)(this)).AddCar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddCarResponse> Client.ServiceReference1.CarWebServiceSoap.AddCarAsync(Client.ServiceReference1.AddCarRequest request) {
            return base.Channel.AddCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.AddCarResponse> AddCarAsync(Client.ServiceReference1.Car car) {
            Client.ServiceReference1.AddCarRequest inValue = new Client.ServiceReference1.AddCarRequest();
            inValue.Body = new Client.ServiceReference1.AddCarRequestBody();
            inValue.Body.car = car;
            return ((Client.ServiceReference1.CarWebServiceSoap)(this)).AddCarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.UpdateCarResponse Client.ServiceReference1.CarWebServiceSoap.UpdateCar(Client.ServiceReference1.UpdateCarRequest request) {
            return base.Channel.UpdateCar(request);
        }
        
        public void UpdateCar(Client.ServiceReference1.Car car, string newModel, string newMarca, string newAnDeFabricatie, string newKm, string newPret, string newPoza) {
            Client.ServiceReference1.UpdateCarRequest inValue = new Client.ServiceReference1.UpdateCarRequest();
            inValue.Body = new Client.ServiceReference1.UpdateCarRequestBody();
            inValue.Body.car = car;
            inValue.Body.newModel = newModel;
            inValue.Body.newMarca = newMarca;
            inValue.Body.newAnDeFabricatie = newAnDeFabricatie;
            inValue.Body.newKm = newKm;
            inValue.Body.newPret = newPret;
            inValue.Body.newPoza = newPoza;
            Client.ServiceReference1.UpdateCarResponse retVal = ((Client.ServiceReference1.CarWebServiceSoap)(this)).UpdateCar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.UpdateCarResponse> Client.ServiceReference1.CarWebServiceSoap.UpdateCarAsync(Client.ServiceReference1.UpdateCarRequest request) {
            return base.Channel.UpdateCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.UpdateCarResponse> UpdateCarAsync(Client.ServiceReference1.Car car, string newModel, string newMarca, string newAnDeFabricatie, string newKm, string newPret, string newPoza) {
            Client.ServiceReference1.UpdateCarRequest inValue = new Client.ServiceReference1.UpdateCarRequest();
            inValue.Body = new Client.ServiceReference1.UpdateCarRequestBody();
            inValue.Body.car = car;
            inValue.Body.newModel = newModel;
            inValue.Body.newMarca = newMarca;
            inValue.Body.newAnDeFabricatie = newAnDeFabricatie;
            inValue.Body.newKm = newKm;
            inValue.Body.newPret = newPret;
            inValue.Body.newPoza = newPoza;
            return ((Client.ServiceReference1.CarWebServiceSoap)(this)).UpdateCarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.DeleteCarResponse Client.ServiceReference1.CarWebServiceSoap.DeleteCar(Client.ServiceReference1.DeleteCarRequest request) {
            return base.Channel.DeleteCar(request);
        }
        
        public void DeleteCar(Client.ServiceReference1.Car car) {
            Client.ServiceReference1.DeleteCarRequest inValue = new Client.ServiceReference1.DeleteCarRequest();
            inValue.Body = new Client.ServiceReference1.DeleteCarRequestBody();
            inValue.Body.car = car;
            Client.ServiceReference1.DeleteCarResponse retVal = ((Client.ServiceReference1.CarWebServiceSoap)(this)).DeleteCar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.DeleteCarResponse> Client.ServiceReference1.CarWebServiceSoap.DeleteCarAsync(Client.ServiceReference1.DeleteCarRequest request) {
            return base.Channel.DeleteCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.DeleteCarResponse> DeleteCarAsync(Client.ServiceReference1.Car car) {
            Client.ServiceReference1.DeleteCarRequest inValue = new Client.ServiceReference1.DeleteCarRequest();
            inValue.Body = new Client.ServiceReference1.DeleteCarRequestBody();
            inValue.Body.car = car;
            return ((Client.ServiceReference1.CarWebServiceSoap)(this)).DeleteCarAsync(inValue);
        }
    }
}
